# Generated by Django 4.2.14 on 2024-08-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_user_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
